In [1]:
import numpy as np
from scipy.stats import norm, t
from matplotlib import pyplot as plt

### Задача 1

Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks):
zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110],
ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832].
Найдите ковариацию этих двух величин с помощью элементарных действий, а затем с помощью функции cov из numpy
Полученные значения должны быть равны.
Найдите коэффициент корреляции Пирсона с помощью ковариации и среднеквадратичных отклонений двух признаков,
а затем с использованием функций из библиотек numpy и pandas.

In [2]:
zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])
n = zp.size

In [3]:
mean_zp = zp.mean()
mean_ks = ks.mean()

In [4]:
zpks = zp * ks
mean_zpks = zpks.mean()

In [5]:
(mean_zpks - mean_zp * mean_ks) * n / (n - 1)

10175.377777777774

In [6]:
np.cov(zp, ks)

array([[ 3882.93333333, 10175.37777778],
       [10175.37777778, 33854.32222222]])

In [7]:
np.cov(zp, ks) / zp.std(ddof=1) / ks.std(ddof=1)

array([[0.33866702, 0.88749009],
       [0.88749009, 2.95275283]])

In [8]:
np.corrcoef(zp, ks)

array([[1.        , 0.88749009],
       [0.88749009, 1.        ]])

### Задача 2

Измерены значения IQ выборки студентов,
обучающихся в местных технических вузах:
131, 125, 115, 122, 131, 115, 107, 99, 125, 111.
Известно, что в генеральной совокупности IQ распределен нормально.
Найдите доверительный интервал для математического ожидания с надежностью 0.95.

In [9]:
data = np.array([131, 125, 115, 122, 131, 115, 107, 99, 125, 111])

In [10]:
alpha = 0.95
n = data.size
m = data.mean()
s = data.std(ddof=1)

In [11]:
t_ = t.ppf(df=n-1, q=(1+alpha)/2)
conf1 = m - t_ * s / np.sqrt(n)
conf2 = m + t_ * s / np.sqrt(n)
conf1, conf2, t_

(110.55608365158724, 125.64391634841274, 2.2621571627409915)

In [12]:
t.interval(alpha=alpha, df=n-1, loc=m, scale=s / np.sqrt(n))

(110.55608365158724, 125.64391634841274)

### Задача 3

Известно, что рост футболистов в сборной распределен нормально
с дисперсией генеральной совокупности, равной 25 кв.см. Объем выборки равен 27,
среднее выборочное составляет 174.2. Найдите доверительный интервал для математического
ожидания с надежностью 0.95.

In [13]:
alpha = 0.95
n = 27
m = 174.2
s = np.sqrt(25)

In [14]:
z = norm.ppf(q=(1+alpha)/2)
conf1 = m - z * s / np.sqrt(n)
conf2 = m + z * s / np.sqrt(n)
conf1, conf2, z

(172.3140237765397, 176.08597622346028, 1.959963984540054)

In [15]:
norm.interval(alpha=0.95, loc=m, scale=s / np.sqrt(n))

(172.3140237765397, 176.08597622346028)